name: Python application testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    env:
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET: ${{ secrets.SECRET }}
      SUPER_USER_TOKEN: ${{ secrets.SUPER_USER_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry export --dev >> requirements.txt
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest tests/ --cov --cov-report=xml -v
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}